export const items = [
    "banana", "apple", "box", "table", "chair", "laptop", "phone", "television", "monitor", "keyboard",
    "mouse", "pen", "pencil", "notebook", "book", "bag", "shoes", "t-shirt", "jacket", "hat",
    "socks", "glasses", "watch", "umbrella", "water", "juice", "coffee", "tea", "sandwich", "cake",
    "cookie", "chips", "apple pie", "carrot", "cucumber", "tomato", "lettuce", "potato", "onion",
    "garlic", "bread", "butter", "cheese", "yogurt", "milk", "eggs", "orange", "strawberry", "kiwi",
    "peach", "plum", "grape", "melon", "watermelon", "pineapple", "mango", "avocado", "cherry",
    "lemon", "lime", "pomegranate", "blueberry", "blackberry", "raspberry", "pear", "fig", "date",
    "papaya", "coconut", "nut", "almond", "cashew", "walnut", "peanut", "chocolate", "vanilla",
    "sugar", "salt", "pepper", "vinegar", "olive oil", "mustard", "ketchup", "mayonnaise", "sriracha",
    "barbecue sauce", "soy sauce", "honey", "maple syrup", "hot sauce", "spaghetti", "pasta", "noodles",
    "rice", "sushi", "taco", "pizza", "burger", "fries", "salad", "soup", "stew", "curry", "pie",
    "roast chicken", "steak", "fish", "shrimp", "lobster", "crab", "scallops", "mussels", "clam", "oyster",
    "tofu", "vegetable", "fruit", "meat", "chicken", "beef", "pork", "lamb", "duck", "turkey", "goat",
    "bacon", "sausage", "ham", "pepperoni", "salami", "chorizo", "spam", "prosciutto", "prosciuttini",
    "chicken nuggets", "fish fingers", "french toast", "waffles", "pancakes", "cereal", "granola",
    "oatmeal", "muesli", "smoothie", "milkshake", "ice cream", "sorbet", "gelato", "frozen yogurt",
    "cookies", "cupcake", "brownie", "donut", "muffin", "pie", "tart", "cheesecake", "churros", "eclair",
    "macaron", "candy", "gummy bears", "jellybean", "chocolate bar", "lollipop", "popcorn", "nachos",
    "cheese sticks", "fruit salad", "vegetable soup", "lasagna", "chili", "gravy", "casserole",
    "biryani", "pilaf", "fried rice", "quinoa", "couscous", "bulgur", "lentils", "beans", "peas",
    "caramel", "whipped cream", "syrup", "jam", "jelly", "marmalade", "chutney", "pickle", "salsa",
    "tartar sauce", "garlic bread", "naan", "bagel", "croissant", "brioche", "pita", "tortilla",
    "wrap", "flatbread", "rice cakes", "crackers", "pretzel", "popcorn", "cheese", "cream cheese",
    "mozzarella", "cheddar", "parmesan", "brie", "goat cheese", "camembert", "feta", "ricotta",
    "cream", "buttermilk", "cottage cheese", "dips", "sauces", "dressings", "broth", "stock",
    "fondue", "queso", "mochi", "baklava", "samosa", "dumplings", "spring roll", "egg roll", "empanada",
    "pierogi", "tapas", "bruschetta", "carpaccio", "charcuterie", "cheese platter", "sushi roll",
    "sashimi", "nigiri", "tempura", "bento", "frittata", "omelette", "quiche", "tiramisu",
    "fondant", "cheese fondue", "vegetarian", "vegan", "gluten free", "organic", "non-GMO",
    "artisanal", "homemade", "fresh", "local", "gourmet", "takeout", "delivery", "restaurant",
    "cafe", "bistro", "bar", "diner", "food truck", "market", "supermarket", "grocery store",
    "gloves", "scarf", "umbrella", "boots", "sandals", "flip flops", "ballet flats", "loafers",
    "moccasins", "heels", "stilettos", "wedges", "sneakers", "running shoes", "cleats", "dress shoes",
    "suit", "tie", "blouse", "skirt", "pants", "jeans", "shorts", "overalls", "sweater", "sweatshirt",
    "cardigan", "hoodie", "tank top", "scarf", "sweatpants", "leggings", "yoga pants", "jumpsuit",
    "dress", "evening gown", "pajamas", "underwear", "bra", "swimsuit", "bikini", "one-piece",
    "beach towel", "toothbrush", "toothpaste", "shampoo", "conditioner", "soap", "lotion",
    "deodorant", "perfume", "sunscreen", "shaving cream", "razor", "towel", "bathrobe", "comb",
    "hair dryer", "hairbrush", "curling iron", "straightener", "mirror", "nail polish", "nail file",
    "nail clippers", "band-aid", "first aid kit", "medication", "thermometer", "syringe",
    "prescription", "vitamins", "pain relievers", "cough syrup", "bandages", "antiseptic", "ointment",
    "scissors", "glue", "tape", "stapler", "hole punch", "paperclips", "binder", "folder", "sticky notes",
    "printer", "scanner", "fax machine", "file cabinet", "post-it notes", "whiteboard", "marker",
    "chalk", "eraser", "chalkboard", "calculator", "agenda", "diary", "journal", "planner",
    "envelope", "letterhead", "address labels", "postcards", "stamp", "address book", "receipt",
    "ticket", "map", "globe", "backpack", "briefcase", "luggage", "duffel bag", "purse", "wallet",
    "coin purse", "keychain", "sunglasses", "headphones", "earbuds", "smartwatch", "camera",
    "tripod", "lens", "flashlight", "batteries", "power bank", "charger", "extension cord",
    "lightbulb", "flash drive", "external hard drive", "speaker", "microphone", "bluetooth speaker",
    "guitar", "piano", "drums", "violin", "flute", "saxophone", "trumpet", "clarinet", "keyboard",
    "tambourine", "xylophone", "accordion", "ukulele", "banjo", "harp", "cello", "bass guitar",
    "trumpet", "trombone", "french horn", "euphonium", "oboe", "mandolin", "kettle", "teapot",
    "coffee maker", "mixer", "blender", "microwave", "toaster", "oven", "stove", "grill",
    "air fryer", "slow cooker", "pressure cooker", "dishwasher", "fridge", "freezer", "coffee grinder",
    "juicer", "water purifier", "bread maker", "rice cooker", "popcorn maker", "frying pan",
    "saucepan", "stockpot", "wok", "griddle", "roasting pan", "baking sheet", "cake pan", "pie dish",
    "loaf pan", "muffin tin", "measuring cups", "measuring spoons", "whisk", "spatula", "tongs",
    "ladle", "strainer", "colander", "peeler", "grater", "knife", "cutting board", "scissors",
    "can opener", "bottle opener", "corkscrew", "garlic press", "mortar and pestle", "salt shaker",
    "pepper mill", "toothpicks", "tea infuser", "ice cream scooper", "butter dish", "sugar bowl",
    "cream pitcher", "salt and pepper shakers", "coasters", "placemats", "napkins", "tablecloth",
    "candles", "matches", "lighter", "incense", "ashtray", "vase", "flowerpot", "succulent", "plant",
    "window box", "tree", "bush", "shrub", "garden", "flowerbed", "yard", "porch", "balcony",
    "deck", "patio", "swimming pool", "fountain", "pond", "birdbath", "swing", "slide", "sandbox",
    "climbing frame", "trampoline", "golf club", "tennis racket", "soccer ball", "basketball",
    "football", "volleyball", "baseball", "baseball bat", "hockey stick", "skateboard",
    "rollerblades", "scooter", "bike", "bicycle", "helmet", "knee pads", "elbow pads", "wrist guards",
    "skis", "ski poles", "snowboard", "snowshoes", "kayak", "canoe", "surfboard", "boogie board",
    "paddleboard", "fishing rod", "tackle box", "hook", "bait", "fishing net", "tent", "sleeping bag",
    "camping stove", "camping lantern", "flashlight", "compass", "map", "binoculars", "backpacking",
    "hiking boots", "trail shoes", "walking stick", "fanny pack", "rucksack", "camping chair",
    "cooler", "sleeping pad", "camping pillow", "cooking pot", "flashlight", "headlamp", "raincoat",
    "weatherproof jacket", "thermals", "wool socks", "gloves", "scarves", "warm hat", "beanie",
    "weatherproof boots", "snow boots", "snow gloves", "windbreaker", "gaiters", "boot liners",
    "camping stove", "propane", "fire starter", "matches", "stove fuel", "water filter", "potable water",
    "solar charger", "tent stakes", "camping mat", "binoculars", "hiking pole", "travel pillow",
    "life jacket", "whistle", "waterproof bag", "thermos", "hydration pack", "backpack rain cover",
    "waterproof boots", "rain pants", "rain jacket", "travel insurance", "passport", "visa",
    "plane ticket", "train ticket", "bus ticket", "boarding pass", "money belt", "travel lock",
    "electrical adapter", "travel plug", "vacuum flask", "passport holder", "sunglasses case",
    "travel wallet", "checklist", "packing cubes", "luggage tag", "ziplock bags", "plastic bags",
    "stain remover", "wrinkle release spray", "laundry detergent", "dryer sheets", "clothesline",
    "laundry basket", "iron", "steamer", "clothes dryer", "clothes rack", "drying rack", "dryer balls",
    "fabric softener", "starch", "clothes hanger", "shoehorn", "shoe polish", "leather cleaner",
    "clothing brush", "deodorant spray", "foot powder", "shoe inserts", "shoe laces", "luggage",
    "travel suitcase", "carry-on bag", "check-in luggage", "duffle bag", "overnight bag", "weekender bag",
    "diaper bag", "laptop case", "tablet case", "briefcase", "backpack", "crossbody bag", "messenger bag",
    "purse", "wallet", "card holder", "money clip", "key holder", "pocket", "belt", "suspenders",
    "tie clip", "watch band", "cufflinks", "collar stays", "belt buckle", "hat pin", "scarf pin",
    "wallet chain", "bracelet", "anklet", "necklace", "ring", "earrings", "brooch", "lapel pin",
    "tie tack", "hairpin", "charm bracelet", "ear cuffs", "bangle", "armband", "pendant", "medallion",
    "dog tag", "neck tie", "bow tie", "shoelace charm", "headband", "bandana", "hair tie", "bracelet",
    "hairband", "necklace holder", "earring holder", "watch display", "jewelry box", "hatbox",
    "keychain", "tote bag", "beach bag", "wallet", "coin purse", "luggage tag", "passport holder",
    "duffel bag", "fanny pack", "card holder", "cell phone case", "camera case", "tablet sleeve",
    "briefcase", "pencil case", "makeup bag", "diaper bag", "lunchbox", "camera bag", "book bag",
    "backpack organizer", "shoe bag", "hiking bag", "sports bag", "gym bag", "travel pouch", "cosmetic bag",
    "gym towel", "bath towel", "hand towel", "kitchen towel", "floor mat", "welcome mat", "doormat",
    "bedspread", "bedcover", "pillowcase", "bedsheet", "blanket", "comforter", "quilt", "duvet",
    "sleeping pad", "pillow", "throw pillow", "cushion", "mattress", "mattress topper", "bed frame",
    "bedside table", "nightstand", "wardrobe", "dresser", "drawer organizer", "clothing rack",
    "closet organizer", "shoe rack", "coat hanger", "jewelry box", "jewelry tray", "mirror", "wall mirror",
    "full-length mirror", "dressing table", "vanity", "picture frame", "photo album", "shelf", "bookcase",
    "wall shelf", "coffee table", "side table", "end table", "console table", "TV stand", "media console",
    "book nook", "storage bin", "storage box", "closet organizer", "storage drawer", "plastic bin",
    "storage basket", "laundry hamper", "vacuum storage bag", "storage jar", "jar lid", "file organizer",
    "filing cabinet", "file folder", "document holder", "binder", "dividers", "portfolio", "notepad",
    "sticky notes", "paper clips", "stapler", "hole punch", "pen holder", "marker set", "whiteboard markers",
    "chalk", "eraser", "board eraser", "clipboard", "pencil sharpener", "ruler", "tape dispenser",
    "glue stick", "adhesive tape", "packing tape", "masking tape", "scotch tape", "bubble wrap",
    "scissors", "cutting mat", "safety cutter", "craft knife", "glue gun", "hot glue sticks", "sewing kit",
    "sewing machine", "thread", "needle", "pin cushion", "buttons", "elastic band", "measuring tape",
    "fabric scissors", "quilt batting", "ribbon", "lace", "embroidered patch", "safety pins",
    "basting pins", "thimble", "clothespins", "clothespin holder", "ironing board", "iron", "iron rest",
    "stain remover", "clothesline", "laundry basket", "dryer sheets", "clothes dryer", "drying rack",
    "clothes hanger", "clothes pins", "ironing board cover", "garment bag", "laundry detergent", "fabric softener",
    "laundry pods", "bleach", "cleaning gloves", "scrubbing brush", "sponge", "cleaning cloth", "mop",
    "broom", "dustpan", "vacuum cleaner", "carpet cleaner", "steam mop", "duster", "cleaning spray",
    "glass cleaner", "disinfectant wipes", "toilet brush", "toilet plunger", "toilet paper", "bathroom cleaner",
    "sink cleaner", "bathtub cleaner", "tile cleaner", "countertop cleaner", "floor cleaner",
    "window cleaner", "furniture polish", "garbage bags", "recycling bin", "trash can", "trash compactor",
    "compost bin", "kitchen cleaner", "oven cleaner", "stove cleaner", "dishwashing liquid", "dishwasher pods",
    "dish rack", "dish towel", "kitchen gloves", "bottle brush", "scrub pad", "kitchen sponge",
    "toothbrush holder", "soap dispenser", "soap dish", "shower caddy", "bath mat", "shower curtain",
    "shower rod", "toilet seat", "bathroom rug", "bathroom trash can", "bathroom organizer",
    "medicine cabinet", "toothpaste holder", "cotton swabs", "cotton balls", "q-tips", "bandages",
    "antiseptic", "ointment", "medication", "first aid kit", "pill organizer", "thermometer", "face mask",
    "hand sanitizer", "cotton pads", "nail file", "nail clippers", "hairbrush", "comb", "hair clip",
    "hairband", "hair tie", "bobby pins", "hair pins", "shampoo", "conditioner", "dry shampoo",
    "hair gel", "hair mousse", "hair spray", "shaving cream", "razor", "toothbrush", "toothpaste",
    "mouthwash", "floss", "dental picks", "tooth whitening kit", "deodorant", "perfume", "body spray",
    "body lotion", "hand lotion", "lip balm", "chapstick", "sunscreen", "sunblock", "self-tanner",
    "makeup remover", "face wipes", "cleansing brush", "face mask", "facial scrub", "moisturizer",
    "toner", "serum", "foundation", "concealer", "blush", "bronzer", "eyeshadow", "lipstick", "lip gloss",
    "lip liner", "mascara", "eyeliner", "eyebrow pencil", "nail polish", "nail polish remover", "cuticle oil",
    "makeup bag", "makeup brush", "makeup sponge", "hair dryer", "flat iron", "curling iron",
    "hair straightener", "electric razor", "epilator", "electric toothbrush", "shaver", "hair roller",
    "hair dryer diffuser", "bathrobe", "slippers", "bath towel", "hand towel", "washcloth",
    "face towel", "shower towel", "loofah", "body scrubber", "bath sponge", "bath salts", "essential oils",
    "scented candles", "bath bomb", "bubble bath", "foot scrub", "nail polish remover pads", "tissue box",
    "sanitary pads", "tampons", "pantyliners", "baby wipes", "wet wipes", "humidifier", "dehumidifier",
    "air purifier", "electric fan", "space heater", "air conditioner", "electric kettle", "water heater",
    "coffee maker", "espresso machine", "tea kettle", "blender", "food processor", "mixer",
    "hand blender", "microwave", "toaster", "toaster oven", "oven", "stovetop", "dishwasher",
    "refrigerator", "freezer", "fridge", "ice maker", "ice cream maker", "rice cooker",
    "slow cooker", "pressure cooker", "deep fryer", "coffee grinder", "juicer", "food scale",
    "measuring cups", "measuring spoons", "baking pan", "muffin tin", "cake pan", "bread maker",
    "cooking thermometer", "oil dispenser", "vinegar bottle", "salt shaker", "pepper grinder",
    "butter dish", "sugar bowl", "cereal bowl", "dinner plate", "side plate", "salad bowl",
    "glass jar", "plastic container", "storage jar", "ceramic pot", "spice jar", "tea box",
    "coffee jar", "salt container", "flour jar", "sugar jar", "waste bin", "recycling bin",
    "compost bin", "grill", "grill pan", "smoker", "BBQ utensils", "tongs", "spatula",
    "basting brush", "grilling basket", "grilling mat", "kitchen timer", "cookie jar",
    "bread box", "tea strainer", "coffee filter", "pour over", "espresso cups", "wine glasses",
    "champagne flutes", "beer mugs", "shot glasses", "cocktail glasses", "coffee mugs",
    "tea cups", "juice glasses", "ice cube trays", "wine rack", "liquor cabinet", "bar cart",
    "wine opener", "cocktail shaker", "wine stopper", "cocktail stirrers", "cocktail napkins",
    "bar spoon", "wine glass holder", "cocktail picks", "martini glasses", "whiskey glasses",
    "beer opener", "whiskey decanter", "ice bucket", "wine cooler", "coasters", "mugs",
    "tea infuser", "coffee pot", "soda maker", "coffee cups", "milk frother", "ice cream scoop",
    "dish rack", "teapot", "dishwasher detergent", "kitchen brush", "pot scrubber", "spice rack",
    "tea towels", "laundry detergent", "fabric softener", "dryer balls", "towel warmer"
]
